server:
  port: 8080
spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource
    cluster:
    - key: slave1
      url: jdbc:mysql://localhost:3306/slave1?useUnicode=true&characterEncoding=UTF-8
      idle-timeout: 20000
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource
    - key: slave2
      url: jdbc:mysql://localhost:3306/slave2?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

  type-aliases-package: com.taocaicai.dynamicswitchingdatasource.entity